---
apiVersion: v1
kind: Service
metadata:
  name: vault-load-balancer
  labels:
    app: vault
spec:
  type: LoadBalancer
  loadBalancerIP: {{ env.VAULT_LOAD_BALANCER_ADDRESS }}
  ports:
    - name: http
      port: 8200
    - name: server
      port: 8201
  selector:
    app: vault
