---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: vaultingkube
  namespace: {{ build.profile.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vaultingkube
subjects:
- kind: ServiceAccount
  name: vaultingkube
  namespace: vaultingkube

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: vaultingkube
  namespace: {{ build.profile.namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vaultingkube
  namespace: {{ build.profile.namespace }}
